services:
  - type: web
    name: social-media-api
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn social_media_api.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: social-media-db
          property: connectionString
databases:
  - name: social-media-db
